-keep class com.dexterous.** { *; }
-keep class com.example.my_app.** { *; }
-keep class androidx.core.app.CoreComponentFactory { *; }
-keepattributes Signature
-keepattributes *Annotation*
-keep class sun.misc.Unsafe { *; }
-keep class com.google.gson.** { *; }
-keep class com.google.gson.stream.** { *; }
-keep class com.google.gson.examples.android.model.** { *; }
